<?php
/**
 * @copyright Copyright (c) 2017 Lukas Reschke <lukas@statuscode.ch>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\TermsOfService\Db\Mapper;

use OCP\IL10N;

class LanguageMapper {
	/** @var IL10N */
	private $l10n;

	public function __construct(IL10N $l10n) {
		$this->l10n = $l10n;
	}

	public function getLanguages(): array {
		$mappedLanguages = [
			'aa' => (string)$this->l10n->t('Afar'),
			'ab' => (string)$this->l10n->t('Abkhazian'),
			'ae' => (string)$this->l10n->t('Avestan'),
			'af' => (string)$this->l10n->t('Afrikaans'),
			'ak' => (string)$this->l10n->t('Akan'),
			'am' => (string)$this->l10n->t('Amharic'),
			'an' => (string)$this->l10n->t('Aragonese'),
			'ar' => (string)$this->l10n->t('Arabic'),
			'as' => (string)$this->l10n->t('Assamese'),
			'av' => (string)$this->l10n->t('Avaric'),
			'ay' => (string)$this->l10n->t('Aymara'),
			'az' => (string)$this->l10n->t('Azerbaijani'),
			'ba' => (string)$this->l10n->t('Bashkir'),
			'be' => (string)$this->l10n->t('Belarusian'),
			'bg' => (string)$this->l10n->t('Bulgarian'),
			'bh' => (string)$this->l10n->t('Bihari languages'),
			'bi' => (string)$this->l10n->t('Bislama'),
			'bm' => (string)$this->l10n->t('Bambara'),
			'bn' => (string)$this->l10n->t('Bengali'),
			'bo' => (string)$this->l10n->t('Tibetan'),
			'br' => (string)$this->l10n->t('Breton'),
			'bs' => (string)$this->l10n->t('Bosnian'),
			'ca' => (string)$this->l10n->t('Catalan; Valencian'),
			'ce' => (string)$this->l10n->t('Chechen'),
			'ch' => (string)$this->l10n->t('Chamorro'),
			'co' => (string)$this->l10n->t('Corsican'),
			'cr' => (string)$this->l10n->t('Cree'),
			'cs' => (string)$this->l10n->t('Czech'),
			'cu' => (string)$this->l10n->t('Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
			'cv' => (string)$this->l10n->t('Chuvash'),
			'cy' => (string)$this->l10n->t('Welsh'),
			'da' => (string)$this->l10n->t('Danish'),
			'de' => (string)$this->l10n->t('German'),
			'dv' => (string)$this->l10n->t('Divehi; Dhivehi; Maldivian'),
			'dz' => (string)$this->l10n->t('Dzongkha'),
			'ee' => (string)$this->l10n->t('Ewe'),
			'el' => (string)$this->l10n->t('Greek, Modern (1453-)'),
			'en' => (string)$this->l10n->t('English'),
			'eo' => (string)$this->l10n->t('Esperanto'),
			'es' => (string)$this->l10n->t('Spanish; Castilian'),
			'et' => (string)$this->l10n->t('Estonian'),
			'eu' => (string)$this->l10n->t('Basque'),
			'fa' => (string)$this->l10n->t('Persian'),
			'ff' => (string)$this->l10n->t('Fulah'),
			'fi' => (string)$this->l10n->t('Finnish'),
			'fj' => (string)$this->l10n->t('Fijian'),
			'fo' => (string)$this->l10n->t('Faroese'),
			'fr' => (string)$this->l10n->t('French'),
			'fy' => (string)$this->l10n->t('Western Frisian'),
			'ga' => (string)$this->l10n->t('Irish'),
			'gd' => (string)$this->l10n->t('Gaelic; Scottish Gaelic'),
			'gl' => (string)$this->l10n->t('Galician'),
			'gn' => (string)$this->l10n->t('Guarani'),
			'gu' => (string)$this->l10n->t('Gujarati'),
			'gv' => (string)$this->l10n->t('Manx'),
			'ha' => (string)$this->l10n->t('Hausa'),
			'he' => (string)$this->l10n->t('Hebrew'),
			'hi' => (string)$this->l10n->t('Hindi'),
			'ho' => (string)$this->l10n->t('Hiri Motu'),
			'hr' => (string)$this->l10n->t('Croatian'),
			'ht' => (string)$this->l10n->t('Haitian; Haitian Creole'),
			'hu' => (string)$this->l10n->t('Hungarian'),
			'hy' => (string)$this->l10n->t('Armenian'),
			'hz' => (string)$this->l10n->t('Herero'),
			'ia' => (string)$this->l10n->t('Interlingua (International Auxiliary Language Association)'),
			'id' => (string)$this->l10n->t('Indonesian'),
			'ie' => (string)$this->l10n->t('Interlingue; Occidental'),
			'ig' => (string)$this->l10n->t('Igbo'),
			'ii' => (string)$this->l10n->t('Sichuan Yi; Nuosu'),
			'ik' => (string)$this->l10n->t('Inupiaq'),
			'io' => (string)$this->l10n->t('Ido'),
			'is' => (string)$this->l10n->t('Icelandic'),
			'it' => (string)$this->l10n->t('Italian'),
			'iu' => (string)$this->l10n->t('Inuktitut'),
			'ja' => (string)$this->l10n->t('Japanese'),
			'jv' => (string)$this->l10n->t('Javanese'),
			'ka' => (string)$this->l10n->t('Georgian'),
			'kg' => (string)$this->l10n->t('Kongo'),
			'ki' => (string)$this->l10n->t('Kikuyu; Gikuyu'),
			'kj' => (string)$this->l10n->t('Kuanyama; Kwanyama'),
			'kk' => (string)$this->l10n->t('Kazakh'),
			'kl' => (string)$this->l10n->t('Kalaallisut; Greenlandic'),
			'km' => (string)$this->l10n->t('Central Khmer'),
			'kn' => (string)$this->l10n->t('Kannada'),
			'ko' => (string)$this->l10n->t('Korean'),
			'kr' => (string)$this->l10n->t('Kanuri'),
			'ks' => (string)$this->l10n->t('Kashmiri'),
			'ku' => (string)$this->l10n->t('Kurdish'),
			'kv' => (string)$this->l10n->t('Komi'),
			'kw' => (string)$this->l10n->t('Cornish'),
			'ky' => (string)$this->l10n->t('Kirghiz; Kyrgyz'),
			'la' => (string)$this->l10n->t('Latin'),
			'lb' => (string)$this->l10n->t('Luxembourgish; Letzeburgesch'),
			'lg' => (string)$this->l10n->t('Ganda'),
			'li' => (string)$this->l10n->t('Limburgan; Limburger; Limburgish'),
			'ln' => (string)$this->l10n->t('Lingala'),
			'lo' => (string)$this->l10n->t('Lao'),
			'lt' => (string)$this->l10n->t('Lithuanian'),
			'lu' => (string)$this->l10n->t('Luba-Katanga'),
			'lv' => (string)$this->l10n->t('Latvian'),
			'mg' => (string)$this->l10n->t('Malagasy'),
			'mh' => (string)$this->l10n->t('Marshallese'),
			'mi' => (string)$this->l10n->t('Maori'),
			'mk' => (string)$this->l10n->t('Macedonian'),
			'ml' => (string)$this->l10n->t('Malayalam'),
			'mn' => (string)$this->l10n->t('Mongolian'),
			'mr' => (string)$this->l10n->t('Marathi'),
			'ms' => (string)$this->l10n->t('Malay'),
			'mt' => (string)$this->l10n->t('Maltese'),
			'my' => (string)$this->l10n->t('Burmese'),
			'na' => (string)$this->l10n->t('Nauru'),
			'nb' => (string)$this->l10n->t('BokmOEl, Norwegian; Norwegian BokmOEl'),
			'nd' => (string)$this->l10n->t('Ndebele, North; North Ndebele'),
			'ne' => (string)$this->l10n->t('Nepali'),
			'ng' => (string)$this->l10n->t('Ndonga'),
			'nl' => (string)$this->l10n->t('Dutch; Flemish'),
			'nn' => (string)$this->l10n->t('Norwegian Nynorsk; Nynorsk, Norwegian'),
			'no' => (string)$this->l10n->t('Norwegian'),
			'nr' => (string)$this->l10n->t('Ndebele, South; South Ndebele'),
			'nv' => (string)$this->l10n->t('Navajo; Navaho'),
			'ny' => (string)$this->l10n->t('Chichewa; Chewa; Nyanja'),
			'oc' => (string)$this->l10n->t('Occitan (post 1500)'),
			'oj' => (string)$this->l10n->t('Ojibwa'),
			'om' => (string)$this->l10n->t('Oromo'),
			'or' => (string)$this->l10n->t('Oriya'),
			'os' => (string)$this->l10n->t('Ossetian; Ossetic'),
			'pa' => (string)$this->l10n->t('Panjabi; Punjabi'),
			'pi' => (string)$this->l10n->t('Pali'),
			'pl' => (string)$this->l10n->t('Polish'),
			'ps' => (string)$this->l10n->t('Pushto; Pashto'),
			'pt' => (string)$this->l10n->t('Portuguese'),
			'qu' => (string)$this->l10n->t('Quechua'),
			'rm' => (string)$this->l10n->t('Romansh'),
			'rn' => (string)$this->l10n->t('Rundi'),
			'ro' => (string)$this->l10n->t('Romanian; Moldavian; Moldovan'),
			'ru' => (string)$this->l10n->t('Russian'),
			'rw' => (string)$this->l10n->t('Kinyarwanda'),
			'sa' => (string)$this->l10n->t('Sanskrit'),
			'sc' => (string)$this->l10n->t('Sardinian'),
			'sd' => (string)$this->l10n->t('Sindhi'),
			'se' => (string)$this->l10n->t('Northern Sami'),
			'sg' => (string)$this->l10n->t('Sango'),
			'si' => (string)$this->l10n->t('Sinhala; Sinhalese'),
			'sk' => (string)$this->l10n->t('Slovak'),
			'sl' => (string)$this->l10n->t('Slovenian'),
			'sm' => (string)$this->l10n->t('Samoan'),
			'sn' => (string)$this->l10n->t('Shona'),
			'so' => (string)$this->l10n->t('Somali'),
			'sq' => (string)$this->l10n->t('Albanian'),
			'sr' => (string)$this->l10n->t('Serbian'),
			'ss' => (string)$this->l10n->t('Swati'),
			'st' => (string)$this->l10n->t('Sotho, Southern'),
			'su' => (string)$this->l10n->t('Sundanese'),
			'sv' => (string)$this->l10n->t('Swedish'),
			'sw' => (string)$this->l10n->t('Swahili'),
			'ta' => (string)$this->l10n->t('Tamil'),
			'te' => (string)$this->l10n->t('Telugu'),
			'tg' => (string)$this->l10n->t('Tajik'),
			'th' => (string)$this->l10n->t('Thai'),
			'ti' => (string)$this->l10n->t('Tigrinya'),
			'tk' => (string)$this->l10n->t('Turkmen'),
			'tl' => (string)$this->l10n->t('Tagalog'),
			'tn' => (string)$this->l10n->t('Tswana'),
			'to' => (string)$this->l10n->t('Tonga (Tonga Islands)'),
			'tr' => (string)$this->l10n->t('Turkish'),
			'ts' => (string)$this->l10n->t('Tsonga'),
			'tt' => (string)$this->l10n->t('Tatar'),
			'tw' => (string)$this->l10n->t('Twi'),
			'ty' => (string)$this->l10n->t('Tahitian'),
			'ug' => (string)$this->l10n->t('Uighur; Uyghur'),
			'uk' => (string)$this->l10n->t('Ukrainian'),
			'ur' => (string)$this->l10n->t('Urdu'),
			'uz' => (string)$this->l10n->t('Uzbek'),
			've' => (string)$this->l10n->t('Venda'),
			'vi' => (string)$this->l10n->t('Vietnamese'),
			'vo' => (string)$this->l10n->t('VolapYk'),
			'wa' => (string)$this->l10n->t('Walloon'),
			'wo' => (string)$this->l10n->t('Wolof'),
			'xh' => (string)$this->l10n->t('Xhosa'),
			'yi' => (string)$this->l10n->t('Yiddish'),
			'yo' => (string)$this->l10n->t('Yoruba'),
			'za' => (string)$this->l10n->t('Zhuang; Chuang'),
			'zh' => (string)$this->l10n->t('Chinese'),
			'zu' => (string)$this->l10n->t('Zulu'),
		];

		return $mappedLanguages;
	}

}
