<?php
/**
 * @copyright Copyright (c) 2017 Lukas Reschke <lukas@statuscode.ch>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\TermsAndConditions\Db\Mapper;

use OCP\IL10N;

class LanguageMapper {
	/** @var IL10N */
	private $l10n;
	public function __construct(IL10N $l10n) {
		$this->l10n = $l10n;
	}

	public function getLanguages() {
		$mappedLanguages = [
			'aa' => $this->l10n->t('Afar'),
			'ab' => $this->l10n->t('Abkhazian'),
			'ae' => $this->l10n->t('Avestan'),
			'af' => $this->l10n->t('Afrikaans'),
			'ak' => $this->l10n->t('Akan'),
			'am' => $this->l10n->t('Amharic'),
			'an' => $this->l10n->t('Aragonese'),
			'ar' => $this->l10n->t('Arabic'),
			'as' => $this->l10n->t('Assamese'),
			'av' => $this->l10n->t('Avaric'),
			'ay' => $this->l10n->t('Aymara'),
			'az' => $this->l10n->t('Azerbaijani'),
			'ba' => $this->l10n->t('Bashkir'),
			'be' => $this->l10n->t('Belarusian'),
			'bg' => $this->l10n->t('Bulgarian'),
			'bh' => $this->l10n->t('Bihari languages'),
			'bi' => $this->l10n->t('Bislama'),
			'bm' => $this->l10n->t('Bambara'),
			'bn' => $this->l10n->t('Bengali'),
			'bo' => $this->l10n->t('Tibetan'),
			'br' => $this->l10n->t('Breton'),
			'bs' => $this->l10n->t('Bosnian'),
			'ca' => $this->l10n->t('Catalan; Valencian'),
			'ce' => $this->l10n->t('Chechen'),
			'ch' => $this->l10n->t('Chamorro'),
			'co' => $this->l10n->t('Corsican'),
			'cr' => $this->l10n->t('Cree'),
			'cs' => $this->l10n->t('Czech'),
			'cu' => $this->l10n->t('Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
			'cv' => $this->l10n->t('Chuvash'),
			'cy' => $this->l10n->t('Welsh'),
			'da' => $this->l10n->t('Danish'),
			'de' => $this->l10n->t('German'),
			'dv' => $this->l10n->t('Divehi; Dhivehi; Maldivian'),
			'dz' => $this->l10n->t('Dzongkha'),
			'ee' => $this->l10n->t('Ewe'),
			'el' => $this->l10n->t('Greek, Modern (1453-)'),
			'en' => $this->l10n->t('English'),
			'eo' => $this->l10n->t('Esperanto'),
			'es' => $this->l10n->t('Spanish; Castilian'),
			'et' => $this->l10n->t('Estonian'),
			'eu' => $this->l10n->t('Basque'),
			'fa' => $this->l10n->t('Persian'),
			'ff' => $this->l10n->t('Fulah'),
			'fi' => $this->l10n->t('Finnish'),
			'fj' => $this->l10n->t('Fijian'),
			'fo' => $this->l10n->t('Faroese'),
			'fr' => $this->l10n->t('French'),
			'fy' => $this->l10n->t('Western Frisian'),
			'ga' => $this->l10n->t('Irish'),
			'gd' => $this->l10n->t('Gaelic; Scottish Gaelic'),
			'gl' => $this->l10n->t('Galician'),
			'gn' => $this->l10n->t('Guarani'),
			'gu' => $this->l10n->t('Gujarati'),
			'gv' => $this->l10n->t('Manx'),
			'ha' => $this->l10n->t('Hausa'),
			'he' => $this->l10n->t('Hebrew'),
			'hi' => $this->l10n->t('Hindi'),
			'ho' => $this->l10n->t('Hiri Motu'),
			'hr' => $this->l10n->t('Croatian'),
			'ht' => $this->l10n->t('Haitian; Haitian Creole'),
			'hu' => $this->l10n->t('Hungarian'),
			'hy' => $this->l10n->t('Armenian'),
			'hz' => $this->l10n->t('Herero'),
			'ia' => $this->l10n->t('Interlingua (International Auxiliary Language Association)'),
			'id' => $this->l10n->t('Indonesian'),
			'ie' => $this->l10n->t('Interlingue; Occidental'),
			'ig' => $this->l10n->t('Igbo'),
			'ii' => $this->l10n->t('Sichuan Yi; Nuosu'),
			'ik' => $this->l10n->t('Inupiaq'),
			'io' => $this->l10n->t('Ido'),
			'is' => $this->l10n->t('Icelandic'),
			'it' => $this->l10n->t('Italian'),
			'iu' => $this->l10n->t('Inuktitut'),
			'ja' => $this->l10n->t('Japanese'),
			'jv' => $this->l10n->t('Javanese'),
			'ka' => $this->l10n->t('Georgian'),
			'kg' => $this->l10n->t('Kongo'),
			'ki' => $this->l10n->t('Kikuyu; Gikuyu'),
			'kj' => $this->l10n->t('Kuanyama; Kwanyama'),
			'kk' => $this->l10n->t('Kazakh'),
			'kl' => $this->l10n->t('Kalaallisut; Greenlandic'),
			'km' => $this->l10n->t('Central Khmer'),
			'kn' => $this->l10n->t('Kannada'),
			'ko' => $this->l10n->t('Korean'),
			'kr' => $this->l10n->t('Kanuri'),
			'ks' => $this->l10n->t('Kashmiri'),
			'ku' => $this->l10n->t('Kurdish'),
			'kv' => $this->l10n->t('Komi'),
			'kw' => $this->l10n->t('Cornish'),
			'ky' => $this->l10n->t('Kirghiz; Kyrgyz'),
			'la' => $this->l10n->t('Latin'),
			'lb' => $this->l10n->t('Luxembourgish; Letzeburgesch'),
			'lg' => $this->l10n->t('Ganda'),
			'li' => $this->l10n->t('Limburgan; Limburger; Limburgish'),
			'ln' => $this->l10n->t('Lingala'),
			'lo' => $this->l10n->t('Lao'),
			'lt' => $this->l10n->t('Lithuanian'),
			'lu' => $this->l10n->t('Luba-Katanga'),
			'lv' => $this->l10n->t('Latvian'),
			'mg' => $this->l10n->t('Malagasy'),
			'mh' => $this->l10n->t('Marshallese'),
			'mi' => $this->l10n->t('Maori'),
			'mk' => $this->l10n->t('Macedonian'),
			'ml' => $this->l10n->t('Malayalam'),
			'mn' => $this->l10n->t('Mongolian'),
			'mr' => $this->l10n->t('Marathi'),
			'ms' => $this->l10n->t('Malay'),
			'mt' => $this->l10n->t('Maltese'),
			'my' => $this->l10n->t('Burmese'),
			'na' => $this->l10n->t('Nauru'),
			'nb' => $this->l10n->t('BokmŒl, Norwegian; Norwegian BokmŒl'),
			'nd' => $this->l10n->t('Ndebele, North; North Ndebele'),
			'ne' => $this->l10n->t('Nepali'),
			'ng' => $this->l10n->t('Ndonga'),
			'nl' => $this->l10n->t('Dutch; Flemish'),
			'nn' => $this->l10n->t('Norwegian Nynorsk; Nynorsk, Norwegian'),
			'no' => $this->l10n->t('Norwegian'),
			'nr' => $this->l10n->t('Ndebele, South; South Ndebele'),
			'nv' => $this->l10n->t('Navajo; Navaho'),
			'ny' => $this->l10n->t('Chichewa; Chewa; Nyanja'),
			'oc' => $this->l10n->t('Occitan (post 1500)'),
			'oj' => $this->l10n->t('Ojibwa'),
			'om' => $this->l10n->t('Oromo'),
			'or' => $this->l10n->t('Oriya'),
			'os' => $this->l10n->t('Ossetian; Ossetic'),
			'pa' => $this->l10n->t('Panjabi; Punjabi'),
			'pi' => $this->l10n->t('Pali'),
			'pl' => $this->l10n->t('Polish'),
			'ps' => $this->l10n->t('Pushto; Pashto'),
			'pt' => $this->l10n->t('Portuguese'),
			'qu' => $this->l10n->t('Quechua'),
			'rm' => $this->l10n->t('Romansh'),
			'rn' => $this->l10n->t('Rundi'),
			'ro' => $this->l10n->t('Romanian; Moldavian; Moldovan'),
			'ru' => $this->l10n->t('Russian'),
			'rw' => $this->l10n->t('Kinyarwanda'),
			'sa' => $this->l10n->t('Sanskrit'),
			'sc' => $this->l10n->t('Sardinian'),
			'sd' => $this->l10n->t('Sindhi'),
			'se' => $this->l10n->t('Northern Sami'),
			'sg' => $this->l10n->t('Sango'),
			'si' => $this->l10n->t('Sinhala; Sinhalese'),
			'sk' => $this->l10n->t('Slovak'),
			'sl' => $this->l10n->t('Slovenian'),
			'sm' => $this->l10n->t('Samoan'),
			'sn' => $this->l10n->t('Shona'),
			'so' => $this->l10n->t('Somali'),
			'sq' => $this->l10n->t('Albanian'),
			'sr' => $this->l10n->t('Serbian'),
			'ss' => $this->l10n->t('Swati'),
			'st' => $this->l10n->t('Sotho, Southern'),
			'su' => $this->l10n->t('Sundanese'),
			'sv' => $this->l10n->t('Swedish'),
			'sw' => $this->l10n->t('Swahili'),
			'ta' => $this->l10n->t('Tamil'),
			'te' => $this->l10n->t('Telugu'),
			'tg' => $this->l10n->t('Tajik'),
			'th' => $this->l10n->t('Thai'),
			'ti' => $this->l10n->t('Tigrinya'),
			'tk' => $this->l10n->t('Turkmen'),
			'tl' => $this->l10n->t('Tagalog'),
			'tn' => $this->l10n->t('Tswana'),
			'to' => $this->l10n->t('Tonga (Tonga Islands)'),
			'tr' => $this->l10n->t('Turkish'),
			'ts' => $this->l10n->t('Tsonga'),
			'tt' => $this->l10n->t('Tatar'),
			'tw' => $this->l10n->t('Twi'),
			'ty' => $this->l10n->t('Tahitian'),
			'ug' => $this->l10n->t('Uighur; Uyghur'),
			'uk' => $this->l10n->t('Ukrainian'),
			'ur' => $this->l10n->t('Urdu'),
			'uz' => $this->l10n->t('Uzbek'),
			've' => $this->l10n->t('Venda'),
			'vi' => $this->l10n->t('Vietnamese'),
			'vo' => $this->l10n->t('VolapŸk'),
			'wa' => $this->l10n->t('Walloon'),
			'wo' => $this->l10n->t('Wolof'),
			'xh' => $this->l10n->t('Xhosa'),
			'yi' => $this->l10n->t('Yiddish'),
			'yo' => $this->l10n->t('Yoruba'),
			'za' => $this->l10n->t('Zhuang; Chuang'),
			'zh' => $this->l10n->t('Chinese'),
			'zu' => $this->l10n->t('Zulu'),
		];

		return $mappedLanguages;
	}

}
